"""empty message

Revision ID: 26ed93aa2cfe
Revises: ce55c6912e68
Create Date: 2023-02-02 11:44:26.734763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ed93aa2cfe'
down_revision = 'ce55c6912e68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
