"""empty message

Revision ID: 4bbab02db9e5
Revises: 6f53add35bae
Create Date: 2023-02-02 11:55:13.396391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbab02db9e5'
down_revision = '6f53add35bae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
