"""empty message

Revision ID: 6f53add35bae
Revises: 26ed93aa2cfe
Create Date: 2023-02-02 11:48:42.863156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f53add35bae'
down_revision = '26ed93aa2cfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices_items', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices_items', 'invoice_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
