"""empty message

Revision ID: 972dc11fe039
Revises: 40deb421dabd
Create Date: 2022-09-28 13:16:32.019460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972dc11fe039'
down_revision = '40deb421dabd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
