"""empty message

Revision ID: 991dd1d6c2cb
Revises: f980c2d4566c
Create Date: 2023-02-02 12:06:41.278914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991dd1d6c2cb'
down_revision = 'f980c2d4566c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
