"""empty message

Revision ID: bef63d754b30
Revises: 991dd1d6c2cb
Create Date: 2023-02-02 12:08:24.537900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef63d754b30'
down_revision = '991dd1d6c2cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices_items', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('invoices_items', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('invoices_items', sa.Column('unity_price', sa.Float(), nullable=False))
    op.add_column('invoices_items', sa.Column('delivered', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'invoices_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices_items', type_='foreignkey')
    op.drop_column('invoices_items', 'delivered')
    op.drop_column('invoices_items', 'unity_price')
    op.drop_column('invoices_items', 'quantity')
    op.drop_column('invoices_items', 'product_id')
    # ### end Alembic commands ###
