"""empty message

Revision ID: ce55c6912e68
Revises: edac80da5cfc
Create Date: 2023-02-01 20:05:38.569155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce55c6912e68'
down_revision = 'edac80da5cfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('table_user', sa.String(), nullable=False),
    sa.Column('table_password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Tables')
    op.add_column('invoices', sa.Column('table_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'invoices', 'tables', ['table_id'], ['id'])
    op.drop_column('invoices', 'table_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'table_id')
    op.create_table('Tables',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Tables_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_user', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='Tables_store_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Tables_pkey')
    )
    op.drop_table('tables')
    # ### end Alembic commands ###
