"""empty message

Revision ID: edac80da5cfc
Revises: d944ba11aac8
Create Date: 2023-02-01 16:52:30.374667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edac80da5cfc'
down_revision = 'd944ba11aac8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('table_name', sa.String(), nullable=False))
    op.drop_column('invoices', 'table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('table', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('invoices', 'table_name')
    # ### end Alembic commands ###
