"""empty message

Revision ID: ee09966d93bc
Revises: 4bbab02db9e5
Create Date: 2023-02-02 11:57:59.850304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee09966d93bc'
down_revision = '4bbab02db9e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
